#!/bin/bash
#
# Short:    Perform pre-install checks
# Author:   Mark J Swift
# Version:  1.0.1
# Modified: 01-Jan-2017
#
#
# Called as follows (as root):    
#   PreInstall

# need to pass volume

# ---

# Full souce of this script
sv_ThisScriptFilePath="${0}"

# Path to this script
sv_ThisScriptDirPath="$(dirname "${sv_ThisScriptFilePath}")"

# Filename of this script
sv_ThisScriptFileName="$(basename "${sv_ThisScriptFilePath}")"

# ---

# Filename without extension
GLB_sv_ThisScriptName="$(echo ${sv_ThisScriptFileName} | sed 's|\.[^.]*$||')"

# Path to project files
GLB_sv_ProjectDirPath="$(dirname "${sv_ThisScriptDirPath}")"

# Include the CommonLib
. "${GLB_sv_ProjectDirPath}/lib/CommonLib"

# Exit if something went wrong unexpectedly
if test -z "${GLB_sv_ProjectName}"
then
  exit 0
fi

# ---

# Where we should install
sv_RootDirPath="${1}"

if [ "${sv_RootDirPath}" = "/" ]
then
  sv_RootDirPath=""
fi

# ---

# Exit if not the root user
if [ "${GLB_sv_ThisUserName}" != "root" ]
then
  exit 0
fi

# ---

GLB_nf_logmessage "NOTE: Performing post-install checks"

if test -z "${sv_RootDirPath}"
then

  if test -f /Library/LaunchDaemons/${GLB_sv_ProjectSignature}.CheckHooks.plist
  then
    launchctl load /Library/LaunchDaemons/${GLB_sv_ProjectSignature}.CheckHooks.plist
  fi

  if test -z "$(launchctl list | grep "${GLB_sv_ProjectSignature}.CheckHooks")"
  then
    GLB_nf_logmessage "ERROR: Unable to install. ${GLB_sv_ProjectName} failed to start."
  "${GLB_sv_ProjectDirPath}/util/Uninstall.command"
    exit 99
  fi

fi

# ---

GLB_nf_logmessage "NOTE: ${GLB_sv_ProjectName} installed OK."

"${GLB_sv_ProjectDirPath}/scripts/CheckHooks"

exit 0

