#!/bin/bash
#
# Short:    Perform pre-install checks
# Author:   Mark J Swift
# Version:  1.0.3
# Modified: 11-Apr-2017
#
#
# Called as follows (by Install as root):    
#   PreInstall

# ---

# assume that all scripts are in a subdirectory off the main project directory
GLB_sv_ProjectDirPath="$(dirname $(dirname ${0}))"

# Include the CommonLib
. "${GLB_sv_ProjectDirPath}/inc/Common.sh"

# Exit if something went wrong unexpectedly
if test -z "${GLB_sv_ProjectName}"
then
  exit 90
fi

# ---

# Exit if not the root user
if [ "${GLB_sv_ThisUserName}" != "root" ]
then
  GLB_nf_logmessage ${GLB_iv_MsgLevelErr} "Unable to run, try: sudo ${GLB_sv_ThisScriptName}"
  exit 91
fi

# ---

# Where we should install
sv_RootDirPath="${1}"

if [ "${sv_RootDirPath}" = "/" ]
then
  sv_RootDirPath=""
fi

# ---

GLB_nf_logmessage ${GLB_iv_MsgLevelInfo} "Performing pre-install checks"

if test -z "${sv_RootDirPath}"
then

  if test -n "$(launchctl list | grep "${GLB_sv_ProjectSignature}.CheckHooks")"
  then
    GLB_nf_logmessage ${GLB_iv_MsgLevelWarn} "Unable to install. ${GLB_sv_ProjectName} is already installed and running."
    exit 92
  fi

  # Do a quick check to see if some other process is regularly updating the hooks

  # Get the existing Login and Logout hooks
  sv_ExistingLoginHookFilePath="$(defaults read com.apple.loginwindow LoginHook)"
  sv_ExistingLogoutHookFilePath="$(defaults read com.apple.loginwindow LogoutHook)"

  # Clear the Login and Logout hooks
  defaults write com.apple.loginwindow LoginHook ""
  defaults write com.apple.loginwindow LogoutHook ""

  # Wait around a bit
  sleep 4

  # Re-read the hooks - they should still be null
  sv_CurrentLoginHookFilePath="$(defaults read com.apple.loginwindow LoginHook)"
  sv_CurrentLogoutHookFilePath="$(defaults read com.apple.loginwindow LogoutHook)"

  # Restore original hooks
  defaults write com.apple.loginwindow LoginHook "${sv_ExistingLoginHookFilePath}"
  defaults write com.apple.loginwindow LogoutHook "${sv_ExistingLogoutHookFilePath}"

  if test -n "${sv_CurrentLoginHookFilePath}${sv_CurrentLogoutHookFilePath}"
  then
    GLB_nf_logmessage ${GLB_iv_MsgLevelErr} "Unable to install. Something else is already managing the LoginHooks."
    exit 93
  fi

fi

GLB_nf_logmessage ${GLB_iv_MsgLevelInfo} "OK to install."

exit 0

